name: 스토리북 chromatic 배포

on:
  pull_request:
  push:
    branches: [main]

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          #if use checkout@v2, https://github.com/marketplace/actions/publish-to-chromatic#checkout-depth
          fetch-depth: 0

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependency
        run: yarn install

      - name: Publish Chromatic
        id: publish_chromatic
        uses: chromaui/action@v1
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Find Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: 스토리북으로 확인하기

      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✨✨ 스토리북으로 확인하기 ✨✨
            - [Build](${{ steps.publish_chromatic.outputs.buildUrl }})
            - [Preview](${{ steps.publish_chromatic.outputs.storybookUrl }})
          edit-mode: replace
